# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('tipus', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['tipus'],
            },
        ),
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titol', models.CharField(max_length=100, verbose_name='Titol Noticia')),
                ('cos', models.TextField(verbose_name='Cos Noticia')),
                ('font', models.URLField(verbose_name='Font')),
                ('data_pub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publicacio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotografies')),
            ],
            options={
                'verbose_name_plural': 'Notícies',
                'ordering': ['titol'],
            },
        ),
    ]
