# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestoria', '0002_delete_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['titol'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cos',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_pub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='font',
            field=models.URLField(verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titol',
            field=models.CharField(max_length=100, verbose_name='Head'),
        ),
    ]
