# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoria', '0003_auto_20170620_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='font',
            field=models.URLField(blank=True, null=True, verbose_name='Source'),
        ),
    ]
