# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 15:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestoria', '0004_auto_20170620_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cos',
            field=ckeditor.fields.RichTextField(verbose_name='Body'),
        ),
    ]
