# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestoria', '0005_auto_20170719_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data_pub'], 'verbose_name_plural': 'News'},
        ),
    ]
