# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usuari', models.CharField(max_length=100, verbose_name='Nom Usuari')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom propi')),
                ('cognoms', models.CharField(max_length=100, verbose_name='Cognoms')),
                ('correu', models.EmailField(max_length=254, verbose_name='@')),
                ('nif', models.CharField(max_length=9, null=True, verbose_name='NiF')),
                ('direcc', models.CharField(max_length=100, verbose_name='Adreça')),
                ('telf_1', models.CharField(max_length=9, null=True, verbose_name='Telf.')),
                ('telf_2', models.CharField(max_length=9, null=True, verbose_name='Telf.')),
                ('fax', models.CharField(max_length=9, null=True, verbose_name='Telf.')),
                ('arx_1', models.FileField(blank=True, null=True, upload_to='nomines', verbose_name='PdF')),
                ('arx_2', models.FileField(blank=True, null=True, upload_to='altres', verbose_name='Extra Files')),
                ('alta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            options={
                'ordering': ['nom_usuari'],
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
