# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fax',
            field=models.CharField(max_length=9, null=True, verbose_name='Fax'),
        ),
    ]
