# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_auto_20170629_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nom_usuari',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
