# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0003_auto_20170629_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='alta',
        ),
    ]
