# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0005_auto_20170630_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nom_usuari'], 'verbose_name_plural': 'Profile'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cognoms',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='correu',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='direcc',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nif',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telf_1',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telf_2',
        ),
    ]
