# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0006_auto_20170711_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['correu'], 'verbose_name_plural': 'Profile'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='cognoms',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Cognoms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='correu',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='@'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='direcc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Adreça'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='fax',
            field=models.CharField(max_length=9, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nif',
            field=models.CharField(max_length=9, null=True, verbose_name='NiF'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nom propi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='telf_1',
            field=models.CharField(max_length=9, null=True, verbose_name='Telf.'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telf_2',
            field=models.CharField(max_length=9, null=True, verbose_name='Telf.'),
        ),
    ]
