# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0007_auto_20170711_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cognoms',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nom',
        ),
    ]
