# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuaris', '0008_auto_20170711_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='arxius',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom arxiu')),
                ('arx_1', models.FileField(blank=True, null=True, upload_to='nomines', verbose_name='PdF')),
                ('nom_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Altri')),
                ('arx_2', models.FileField(blank=True, null=True, upload_to='altres', verbose_name='Extra Files')),
                ('data_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_pub'],
                'verbose_name_plural': 'Arxius',
            },
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='arx_1',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='arx_2',
        ),
    ]
