# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0009_auto_20170711_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telf_2',
        ),
        migrations.AddField(
            model_name='perfil',
            name='pobl',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Ciutat'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fax',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='NiF'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telf_1',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Telf.'),
        ),
    ]
