# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0010_auto_20170712_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arxius',
            name='arx_2',
        ),
        migrations.RemoveField(
            model_name='arxius',
            name='nom_2',
        ),
    ]
