# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0011_auto_20170714_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arxius',
            options={'ordering': ['-data_pub'], 'verbose_name_plural': 'PdF'},
        ),
    ]
