# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0012_auto_20170714_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arxius',
            options={'ordering': ['-data_pub'], 'verbose_name_plural': 'Descàrregues'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['correu'], 'verbose_name_plural': 'Dades addicionals'},
        ),
    ]
