# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0015_auto_20170803_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nom_usuari'], 'verbose_name_plural': 'Dades addicionals'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='correu',
        ),
    ]
